- type: replace
  path: /instance_groups/name=ingestor/jobs/name=ingestor_syslog/properties/logstash_parser/filters?
  value:
  - uaa-setup: /var/vcap/packages/logsearch-customization-overrides/uaa-setup.conf
  - logsearch-for-cf: /var/vcap/packages/logsearch-config-logstash-filters/logstash-filters-default.conf
  - logsearch-cef-audits: /var/vcap/packages/logsearch-customization-overrides/cef-filters.conf

- type: replace
  path: /instance_groups/name=ingestor/jobs/name=ingestor_syslog/release
  value: logsearch-customizations

- type: replace
  path: /instance_groups/name=kibana/jobs/name=kibana-auth-plugin/release
  value: logsearch-customizations

- type: replace
  path: /instance_groups/name=ingestor/jobs/name=ingestor_syslog/properties/logstash_parser/default_overrides?
  value: |
    output {
      elasticsearch {
          hosts => ["127.0.0.1:9200"]
          index => "logs-%{[@metadata][index]}-%{+YYYY.MM.dd}"
          manage_template => false
      }

      if "audit" in [tags] {
          elasticsearch {
              hosts => ["127.0.0.1:9200"]
              index => "logs-%{@type}-%{+YYYY.MM.dd}"
              manage_template => false
          }
      }
    }

- type: replace
  path: /instance_groups/name=ingestor/jobs/-
  value:
    name: package-loader
    release: logsearch-customizations

- type: replace
  path: /instance_groups/name=maintenance/jobs/-
  value:
    name: audit-kibana-objects
    release: logsearch-customizations
    consumes:
      cloud_controller: {from: cloud_controller, deployment: cf}
      elasticsearch: {from: elasticsearch_master}
    properties:
      cloudfoundry:
        user: admin
        password: "((cf_admin_password))"

- type: replace
  path: /instance_groups/name=maintenance/jobs/name=audit-kibana-objects/consumes/cloud_controller/deployment?
  value: ((cf_deployment_name))

- type: replace
  path: /releases/name=bpm/version
  value: latest

- type: replace
  path: /releases/-
  value:
    name: logsearch-customizations
    version: latest

- type: remove
  path: /releases/name=bpm/url

- type: remove
  path: /releases/name=bpm/sha1

- type: replace
  path: /releases/name=routing/version
  value: latest

- type: remove
  path: /releases/name=routing/url

- type: remove
  path: /releases/name=routing/sha1